### ISSUE TITLE
slide code mismatch with what the demo button really does in javascript lecture!!

### ISSUE THREAD

**Issue by alirezaAsadi2018** [SBU-CE/IE-lecture#10]
Hi! In [47.2](https://sbu-ce.github.io/IE-lecture/slides/lecture-5/index.html#/47/1), I expect the `onclick="document.body.style.backgroundColor =
this.innerHTML;"` for Green button to change the background color of the `body` as the code declares, but when I click it here: [47.3](https://sbu-ce.github.io/IE-lecture/slides/lecture-5/index.html#/47/2), it just changes its own color:
![Screenshot (763)](https://user-images.githubusercontent.com/44492608/99903861-6abb0200-2cdc-11eb-9c0c-2c3c0b6202ab.png)

I suggest that we change [47.2](https://sbu-ce.github.io/IE-lecture/slides/lecture-5/index.html#/47/1) to: `onclick="this.style.backgroundColor = this.innerHTML;"`

**Comment by 1995parham** [comment]
Thanks for mentioning this. I have fixed it.
