### ISSUE TITLE
more about concurrency model in javascript

### ISSUE THREAD

**Issue by rsharifnasab** [SBU-CE/IE-lecture#14]
Hi 
In my opinion, `async` and `await` keywords are good topic to be added in slides. 
Or at least it can be added to "further reading" or something like this. 

Also more examples about `promise` and `resolve` could be helpful. for example these topics maybe good:
1. creating new promise 
2. more information about resolving and rejecting promises 
3. different states of a promise
4. `Promise.all` method
5. more about promise chaining and its best practices 

thanks for your attention.

**Comment by 1995parham** [comment]
I will try to add them for the next semester.

**Comment by 1995parham** [comment]
For Nowruz, I am going to add these topics into Javascript slides. If there are more topics in your mind, let me know.

**Comment by rsharifnasab** [comment]
Thank you really much, I don't have any specific idea about that in my mind 
but I will ask some folks about that.

**Comment by rsharifnasab** [comment]
these are 2 (minor) topics to think about:
+ `strict mode`, probably not for everyday use but for keeping in mind for debugging or dealing with legacy code. ([brief explain](https://flaviocopes.com/javascript-strict-mode/))
+ `async` and `defer` while loading script in html (explained [here](https://flaviocopes.com/javascript-async-defer/)).

**Comment by 1995parham** [comment]
I have updated the slides to discuss topics like promises or `strict mode`. in the future, we can also discuss `async`. I will create another issue for that.
