### ISSUE TITLE
set interval and set timeout in javascript slide

### ISSUE THREAD

**Issue by rsharifnasab** [SBU-CE/IE-lecture#15]
Hi
Unfortunately I'm a bit confused about `setTimeout` and `setInterval` methods. 
As i expect, setTimeout would cause just one time run, not **every**.
but in [this line](https://github.com/SBU-CE/IE-lecture/blob/master/slides/lecture-5/index.html#L2560) description is this:
```
Alert "Hello" every 3 seconds (3000 milliseconds)
```
I think `every` should change to `after`.
Am i right?

**Comment by 1995parham** [comment]
Yes you are right it must changed to **after**. I have done it now.
