### ISSUE TITLE
long slides aren't readable

### ISSUE THREAD

**Issue by rsharifnasab** [SBU-CE/IE-lecture#2]
Hello,
some slides like `24` in [lecture2 ](https://sbu-ce.github.io/IE-lecture/slides/lecture-2/index.html#/24) and `3` in [lecture3](https://sbu-ce.github.io/IE-lecture/slides/lecture-3/index.html#/3) are too long so we can't read whole content in normal browser.
do you have any advice?

**Comment by 1995parham** [comment]
Thanks for mentioning this, I will split them vertically.

**Comment by rsharifnasab** [comment]
thank you!
