### ISSUE TITLE
Broken JSON slides

### ISSUE THREAD

**Issue by radinshayanfar** [SBU-CE/IE-lecture#36]
Hi!
Slide number 16.13 in JSON and Thrift lecture (about JSON Schema) and many slides after that are unfortunately broken. Could you please fix them?

Thank you in advance.

**Comment by 1995parham** [comment]
Hi @radinshayanfar jan.

I have fixed it and it seems good to me. can you please check it again?

**Comment by radinshayanfar** [comment]
It looks like this to me (and the next slides are blank):

![image](https://user-images.githubusercontent.com/14641812/148969641-b7ee7ca1-6188-4cdc-b7d0-013f75669bac.png)

**Comment by 1995parham** [comment]
@radinshayanfar you are right, I will fix it now.

**Comment by radinshayanfar** [comment]
@1995parham Thanks a lot!
