### ISSUE TITLE
improvement idea for MIMEtype example in http

### ISSUE THREAD

**Issue by rsharifnasab** [SBU-CE/IE-lecture#4]
I've just reviewing slides!
in [slide 40 of HTTP lecture](https://sbu-ce.github.io/IE-lecture/slides/lecture-2/index.html#/39), we discussed about MIMEtypes. you added en example of image for it's MIMEtype. 

but i think `Check here` isn't a good description for this example.
maybe adding some java-script code that show response of HEAD method on [the resource](https://api.sahebcloud.ir/api/v1/slide/photo/5f691500beaad9694413b8f1) would be better.

**Comment by 1995parham** [comment]
Resolved :man_dancing:
