### ISSUE TITLE
represent problem in bullets in http lecture

### ISSUE THREAD

**Issue by rsharifnasab** [SBU-CE/IE-lecture#5]
In slide [42](https://sbu-ce.github.io/IE-lecture/slides/lecture-2/index.html#/42) and [53](https://sbu-ce.github.io/IE-lecture/slides/lecture-2/index.html#/53) of http lecture, there is an Table of content available.

in this part you used `&` but it represent as `&amp;`. I think it is something related to HTML escape characters.

![slide53](https://user-images.githubusercontent.com/11211946/95760955-83d19b80-0cb8-11eb-910e-302efd65663f.jpg)

do you have any idea to fix it?

**Comment by 1995parham** [comment]
:scream: This shouldn't happen, I think I know.

**Comment by 1995parham** [comment]
Resolved :raised_hands:
