### ISSUE TITLE
confusion in a statement

### ISSUE THREAD

**Issue by alirezaAsadi2018** [SBU-CE/IE-lecture#8]
As mentioned earlier in #7, slide [60](https://sbu-ce.github.io/IE-lecture/slides/lecture-2/index.html#/60) needs some changes to clear the confusion in these lines:

![Screenshot (666)](https://user-images.githubusercontent.com/44492608/96010422-a2699b00-0e4e-11eb-8d5e-95176900ae18.png)

Thank You!

**Comment by rsharifnasab** [comment]
I suggest this:
----
1. Client-side app (browser) request resource from server
2. Server refuses with `401 Unauthorized`
3. Client-side app ask Username&Password from user 
4. Client send User&Pass to server
5. Server authenticates and allows.
----
if there is a misunderstood in my side, please clear me up.
